name: CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        run: >
          sudo apt update -y -qqq ; 
          sudo apt install -y bash wget ca-certificates curl git ; 
          sudo ln -svf bash /bin/sh ; 
          sudo bash .pre ; 
          sudo apt upgrade -fy -qqq
      - name: create
        run: |
          sudo mkdir /home/.tmp
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1.el7.x86_64.tar.xz
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1.el7.x86_64.tar.xz.sha256
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1.el8.x86_64.tar.xz
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1.el8.x86_64.tar.xz.sha256
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1_amd64.tar.xz
          sudo echo 123 > /home/.tmp/haproxy-2.8.0-1_amd64.tar.xz.sha256
      - name: Upload haproxy el8
        run: |
          _repo="$(echo ${{ github.repository }} | awk -F '/' '{print $2}')"
          _haproxy_ver="$(sudo ls -1 /home/.tmp/haproxy-* | sed -e 's|.*haproxy-||g' -e 's|-.*||g' | tail -n1)"
          sudo ls -1 /home/.tmp/haproxy-* | sudo xargs --no-run-if-empty -I '{}' sudo bash .upload_gh -f '{}' -u "${{ github.repository_owner }}" -r "${_repo}" -t "v${_haproxy_ver}" -k "${{ secrets.GITHUB_TOKEN }}"
