name: ip1
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        run: |
          sudo apt update -y -qqq
          sudo apt install -y bash wget ca-certificates curl git iproute2 net-tools
          sudo ln -svf bash /bin/sh
          sudo apt autoremove --purge -y dotnet-apphost-pack-6.0
          sudo apt autoremove --purge -y dotnet-apphost-pack-7.0
          sudo apt autoremove --purge -y dotnet-host
          sudo apt autoremove --purge -y dotnet-hostfxr-6.0
          sudo apt autoremove --purge -y dotnet-hostfxr-7.0
          sudo apt autoremove --purge -y dotnet-runtime-6.0
          sudo apt autoremove --purge -y dotnet-runtime-7.0
          sudo apt autoremove --purge -y dotnet-runtime-deps-6.0
          sudo apt autoremove --purge -y dotnet-runtime-deps-7.0
          sudo apt autoremove --purge -y dotnet-sdk-6.0
          sudo apt autoremove --purge -y dotnet-sdk-7.0
          sudo apt autoremove --purge -y dotnet-targeting-pack-6.0
          sudo apt autoremove --purge -y dotnet-targeting-pack-7.0
          sudo apt autoremove --purge -y google-chrome-stable
          sudo apt autoremove --purge -y google-cloud-sdk
          sudo apt autoremove --purge -y libmono-microsoft-build4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-build-engine4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-build-framework4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-build-tasks-v4.0-4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-build-utilities-v4.0-4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-csharp4.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-visualc10.0-cil
          sudo apt autoremove --purge -y libmono-microsoft-web-infrastructure1.0-cil
          sudo apt autoremove --purge -y libmono-sqlite4.0-cil
          sudo apt autoremove --purge -y libmono-system-json-microsoft4.0-cil
          sudo apt autoremove --purge -y libmspack0
          sudo apt autoremove --purge -y libpq5
          sudo apt autoremove --purge -y libpq-dev
          sudo apt autoremove --purge -y libsybdb5
          sudo apt autoremove --purge -y libz3-4
          sudo apt autoremove --purge -y libz3-dev
          sudo apt autoremove --purge -y microsoft-edge-stable
          sudo apt autoremove --purge -y mono-roslyn
          sudo apt autoremove --purge -y msodbcsql17
          sudo apt autoremove --purge -y mssql-tools
          sudo apt autoremove --purge -y mysql-client
          sudo apt autoremove --purge -y mysql-client-8.0
          sudo apt autoremove --purge -y mysql-client-core-8.0
          sudo apt autoremove --purge -y mysql-common
          sudo apt autoremove --purge -y mysql-server
          sudo apt autoremove --purge -y mysql-server-8.0
          sudo apt autoremove --purge -y mysql-server-core-8.0
          sudo apt autoremove --purge -y nginx
          sudo apt autoremove --purge -y nginx-common
          sudo apt autoremove --purge -y packages-microsoft-prod
          sudo apt autoremove --purge -y php8.1-mysql
          sudo apt autoremove --purge -y php8.1-pgsql
          sudo apt autoremove --purge -y php8.1-sqlite3
          sudo apt autoremove --purge -y postgresql-14
          sudo apt autoremove --purge -y postgresql-client-14
          sudo apt autoremove --purge -y postgresql-client-common
          sudo apt autoremove --purge -y postgresql-common
          sudo apt autoremove --purge -y powermgmt-base
          sudo apt autoremove --purge -y powershell
          sudo apt autoremove --purge -y python3-configobj
          sudo apt autoremove --purge -y shim-signed
          sudo apt autoremove --purge -y firefox
          sudo /bin/rm -fr /usr/share/sbt
          sudo /bin/rm -fr /usr/share/gradle*
          sudo /bin/rm -fr /usr/share/miniconda*
          sudo /bin/rm -fr /usr/share/az_*
          sudo /bin/rm -fr /usr/share/swift*
          sudo /bin/rm -fr /usr/share/dotnet*
          sudo /bin/rm -fr /usr/lib/snapd
          sudo /bin/rm -fr /usr/lib/firefox
          sudo /bin/rm -fr /usr/lib/llvm*
          sudo /bin/rm -fr /usr/lib/mono
          sudo /bin/rm -fr /usr/lib/jvm
          sudo /bin/rm -fr /usr/lib/google-cloud-sdk*
          sudo /bin/rm -fr /opt/containerd
          sudo /bin/rm -fr /opt/mssql-tools
          sudo /bin/rm -fr /opt/google
          sudo /bin/rm -fr /opt/pipx
          sudo /bin/rm -fr /opt/az
          sudo /bin/rm -fr /opt/microsoft
          sudo /bin/rm -fr /usr/local/sqlpackage
          sudo /bin/rm -fr /usr/local/n
          sudo /bin/rm -fr /usr/local/aws*
          sudo /bin/rm -fr /usr/local/julia*
          sudo /bin/rm -fr /usr/local/share
          sudo /bin/rm -fr /usr/local/.ghcup
          sudo /bin/rm -fr /opt/hostedtoolcache

      - name: create
        run: |
          echo
          ip addr
          echo
          ifconfig
          echo
          sudo df -h
          echo
          sudo lsblk
          echo
          sudo ls -la /
          echo
          sudo du -d 1 -h /usr/ | sort -h
          echo
          sudo du -d 1 -h /usr/share/ | sort -h
          echo
          sudo du -d 1 -h /opt/ | sort -h
          echo
          sudo du -d 1 -h /usr/local/lib/ | sort -h
          echo
          sudo du -d 1 -h /usr/lib/ | sort -h
          echo
          sudo dpkg -l | grep -iE 'dotnet|swift|conda|gradle|sbt'
          echo
          sudo dpkg -l | grep -iE 'sql|postgre|google|aws|microsoft|power'
          echo


