name: ip1
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Preinstall
        run: >
          sudo apt update -y -qqq ; 
          sudo apt install -y bash wget ca-certificates curl git iproute2 net-tools ;
          sudo ln -svf bash /bin/sh ; 
      - name: create
        run: |
          echo
          ip addr
          echo
          ifconfig
          echo
          sudo df -h
          echo
          sudo lsblk
          echo
          sudo ls -la /
          echo
          sudo du -d 1 -h / | sort -h
          echo
          sudo du -d 1 -h /usr/ | sort -h
          echo
          sudo du -d 1 -h /usr/share/ | sort -h
          echo
          sudo du -d 1 -h /opt/ | sort -h
          echo
          sudo du -d 1 -h /usr/local/ | sort -h
          echo
          sudo du -d 1 -h /usr/lib/ | sort -h
          echo
          sudo dpkg -l | grep -iE 'dotnet|swift|conda|gradle|sbt'
          echo


